baseURL = "https://whirlwind.netlify.com"
languageCode = "en-us"
title = "From the Whirlwind"
theme = "hugo-xmin"
sectionPagesMenu = "main"

[params]
  featured_image = "/images/tornado.jpg"
  enableRobotsTXT = true
